### ISSUE TITLE
fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory 

### ISSUE THREAD

**Issue by adrianR2** [chartbeat-labs/textacy#19]
I get this error on both install methods, on Windows 8.1, Python 2.7
 pip install -U textacy
and 
python setup.py install

In detail, for  **pip install -U textacy** it shows at the end

    encoding_lut.cc
    cld2\public\compact_lang_det.h(65) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\acer\appdata\local\temp\pip-build-7v3c2_\cld2-cffi\setup.py", line 189, in <module>
```
. . . 
      File "c:\users\acer\appdata\local\temp\pip-build-7v3c2_\cld2-cffi\.eggs\cffi-0.9.2-py2.7-win32.egg\cffi\ffiplatform.py", line 54, in _build
        raise VerificationError('%s: %s' % (e.__class__.__name__, e))
    cffi.ffiplatform.VerificationError: CompileError: command 'C:\\Users\\Acer\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\acer\appdata\local\temp\pip-build-7v3c2_\cld2-cffi\
```

With the second method, **python setup.py install**, the listing ends in

```
encoding_lut.cc
cld2\public\compact_lang_det.h(65) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
error: [Error 5] **Access is denied**: 'c:\\users\\acer\\appdata\\local\\temp\\easy_install-2gzufx\\cld2-cffi-0.1.1\\.eggs\\cffi-0.9.2-py2.7-win32.egg\\_cffi_backend.pyd'
```

Any suggestion would be much appreciated, Thank you. Adrian

**Comment by bdewilde** [comment]
Hi @adrianR2 , I've not used a Windows machine in at least 10 years, so please take all of my comments with a grain of salt. It looks like there's a problem with `cld2-effi`, a dependency of `textacy` used in detecting the language of a given text (see [here](https://pypi.python.org/pypi/cld2-cffi)).

Have you installed that dependency? Can you `import cld2` in your Python interpreter, and does it work?

**Comment by adrianR2** [comment]
Hi Burton, thank you for the reply. Indeed, the error message comes from the attempt installation of cld2-cffi 0.1.2

`pip install cld2-cffi`

 I should contact the author of this package then. Thank you. Adrian,

**Comment by gryBox** [comment]
Hi @adrianR2 - Here was the fix given to me by @bdewilde for the same problem

> Hey @gryBox, sorry about the trouble! I see that you posted on cld2-cffi's github page a week ago, but haven't heard back. Please keep me posted if they respond. I must say, I don't know much about troubleshooting other folks' packages on Windows, but I do have a hack/solution for you on the textacy side.

Fortunately, cld2-cffi is used in textacy only in the text_utils.detect_language() function, which is called automatically when a new TextDoc is initialized without a specified language. If you know the language of the text(s) you'll be working with, passing in the appropriate language code (e.g. "en") will bypass this function and thus the cld2-cffi dependency. If you comment out this line and, I think, remove the dependency from setup.py here, you should be able to install via $ python setup.py install.

This did it for me however

**Comment by bdewilde** [comment]
Thanks, @gryBox ! I don't suppose the `cld2-effi` devs ever got back to you about this, did they? I hate asking users to apply band-aids so that my code can run.

**Comment by gryBox** [comment]
No.  When I looked at the [git](https://github.com/GregBowyer/cld2-cffi/) there wasn't much work done. I basically stopped updating at `textacy 2.0`. It's nice that you care about your whole user base - but in my 40 (inexperienced) hours  of debugging this issue, it has to do with how python talks to the windows machine c compiler (and there could be many of them).  I went down many rabbit holes. @bdewilde   maybe the solution can be added in the `readme`.

**Comment by adrianR2** [comment]
Thanks @gryBox. I removed the 'cld2-cffi' in setup.py 
and I modified both 
\textacy-0.2.2\build\lib\textacy\ text_utils.py
and
\textacy-0.2.2\textacy\ text_utils.py

to 

```
def detect_language(text):
    return "en"
```

The installation seemed to work, however I get now an import error from Python:

```
C:\Anaconda2\Lib\site-packages\textacy\textacy-0.2.2>python setup.py install
. . . 
Installed c:\anaconda2\lib\site-packages\textacy-0.2.2-py2.7.egg
. . . 
Finished processing dependencies for textacy==0.2.2

C:\Anaconda2\Lib\site-packages\textacy\textacy-0.2.2>python
Python 2.7.11 |Anaconda 4.0.0 (32-bit)| (default, Mar  4 2016, 15:18:41) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import textacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textacy\__init__.py", line 10, in <module>
    from textacy import corpora
  File "textacy\corpora\__init__.py", line 1, in <module>
    from . import wikipedia
  File "textacy\corpora\wikipedia.py", line 11, in <module>
    from gensim.corpora.dictionary import Dictionary
**ImportError: No module named gensim.corpora.dictionary**
>>>
```

What did I do wrong ?

**Comment by bdewilde** [comment]
You have to `pip install gensim` before `pip install textacy` because I forgot to list `gensim` in the requirements. This has been fixed in master on GitHub, just not yet in a pypi release. Sorry! I'll be pushing another release soon, but there's no need to wait on me.

**Comment by adrianR2** [comment]
Thank you @bdewilde. After installing `gensim`, two other modules were reported as missing, `ijson` and` cld2`, so I installed `ijson` as well.  The module cld2 was still mentioned  because  of the line 
`from cld2 import detect as cld2_detect`
in \textacy-0.2.2\build\lib\textacy\text_utils.py
Therefore I removed that line too,

Following the example at https://pypi.python.org/pypi/textacy I get errors:
```
>>> import textacy
>>> text ="""Some help from the province will allow Clean Harbours to grow from 8 employees in Saint John to 15. """
>>> textacy.preprocess_text(text, lowercase=True, no_numbers=True, no_punct=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'preprocess_text'
>>> textacy.text_utils.keyword_in_context(text, 'EPICAC', window_width=40)
>>> doc = textacy.TextDoc(text.strip(), lang='auto',metadata={'title': 'EPICAC', 'author': 'Kurt Vonnegut'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "textacy\texts.py", line 77, in __init__
    raise ValueError(msg)
ValueError: TextDoc must be initialized with set([<type 'spacy.tokens.doc.Doc'>, <type 'unicode'>]), not <type 'str'>
>>>
```

Is this example outdated? Where can I find other examples please? Thanks

**Comment by bdewilde** [comment]
Hey @adrianR2, I just (< 1 minute ago) pushed a new version of textacy to pypi. Please try `pip install -U textacy` and see if that works for you. With this version bump, the example code is now also updated. Everything _should_ work, with the exception of this nasty `cld` + Windows problem.

Please let me know, and sorry about the hassle!

**Comment by adrianR2** [comment]
Thank you @bdewilde. 
 `pip install -U textacy` still does not work for me because of cld2, thus I will have to install it with 
`python setup.py install`

I could not find a download link for the textacy 0.2.3 sources on https://pypi.python.org/pypi/textacy though.
Is there a zip available yet?

**Comment by bdewilde** [comment]
Hi @adrianR2, You can download the source for v0.2.3 from https://github.com/chartbeat-labs/textacy/releases/tag/0.2.3 and install via `python setup.py install`, after you've made the couple tweaks for `cld`. Is there a way to throw that zipped source file up on PyPi? Happy to do it, if so!

I'll try to find a fix for this `cld` issue at some point, this is _really_ inconvenient for y'all. It looked to be the best and fastest language detector around, but maybe there's another option... Thanks for working through all these hangups.

**Comment by adrianR2** [comment]
Thank you @bdewilde. it works now on my side too.

> Is there a way to throw that zipped source file up on PyPi?

 I really don't know, I just asked you for a link on PyPi because I saw there "download and unzip the **source tar.gz from PyPi**, then ..."  
Many thanks. Adrian
